mvn install -f ./TacticalCommons/pom.xml
mvn install -f ./TacticalConfigs/pom.xml
mvn install -f ./TacticalCommands/pom.xml
mvn install -f ./TacticalGUI/pom.xml
mvn install -f ./TacticalProtocol/pom.xml
mvn install -f ./TacticalMusic/pom.xml
mvn install -f ./TacticalAPI/pom.xml
mvn install -f ./Tactical/pom.xml
mvn install -f ./pom.xml